### ISSUE TITLE
Need a meaningful module name.

### ISSUE THREAD

**Issue by wats958** [pacifica/pacifica-userinterface-core#14]
Currently Composer has declared that this is "pacifica/userinterface-core". That means that it is creating a module called "userinterface-core". That has no intrinsic meaning, especially when/if this gets moved into the Drupal Gitlab, where the package will then be called "drupal/userinterface-core". 

We need to align the latter part of the composer name with the name of the module, and be sure to keep in mind it may eventually live elsewhere.
Suggest "pacifica/pacifica-core"?

**Comment by dmlb2000** [comment]
This is fine, should the `type` of the composer package also be changed?

**Comment by wats958** [comment]
Yes - I believe Benjamin already has that part captured in his fork's progress.
